id: I955945DF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T13:44:28+00:00'
last_modified: '2022-06-07T12:03:42.004953+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27888
  title: བསྐྱེད་རིམ་སྤྱིའི་རྣམ་བཞག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A422:
      image_group_id: I4682
      title: ''
      total_pages: 194
      order: 1
      base_file: A422.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
